version: 2

models:
  - name: stg_customers
    description: "To rule out duplicate in data"
    columns:
      - name: customer_id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null      